# These are supported funding model platforms


A Call to Build for Humanity
No established support system exists. I do not possess the expertise in every field required to make this system function flawlessly and safely. I cannot do this alone.

We need minds from all disciplines—AI, Mathematics, Biochemistry, Bioinformatics, Genetics, Computer Science, and Data Analysis—to come together and build.

At this moment, there is no financial backing. But what we lack in funding, we must make up for in collective effort. Code. Build. Share. Innovate. Push boundaries.

The vision: A system capable of generating novel proteins, manufactured through fungal CRISPR engineering in clinical settings. Developed within an educational framework, this tool will empower the next generation to pioneer treatments and cures for all diseases.

This is bigger than any one person. It is a call to action for those who dare to create a future where no condition is beyond our ability to heal.

Join us. Make it work.

--- Filler 
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
